// Generated by LiveScript 1.3.1
(function(){
  var request, http, url, fs, getCurrency;
  request = require('request');
  http = require('http');
  url = require('url');
  fs = require('fs');
  getCurrency = function(req, res){
    var currency;
    currency = url.parse(
    req.url);
    currency = currency.pathname.slice(1, currency.length);
    return fs.readFile('buffered.json', function(err, data){
      var parsed;
      if (!err) {
        parsed = JSON.parse(
        data);
        return res.end(
        JSON.stringify(
        parsed[currency].averages));
      }
    });
  };
  request('http://localhost:9999').pipe(fs.createWriteStream('buffered.json')).on('close', function(){
    http.createServer(getCurrency).listen('7777');
    return console.log('Listening on port 7777.');
  });
}).call(this);
